#spring.application.name=demo
spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    h2:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1
      username: sa
      password:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring2?useSSL=false&serverTimezone=UTC
      username: root
      password: