#spring.application.name=demo
spring:
  batch:
    job:
      name: ExportParallelJob
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mysql.sql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useSSL=false&serverTimezone=UTC
    username: root
    password:

logging:
  level:
    '[com.example.demo': debug

mybatis:
  mapper-locations: classpath*:/mapper/mysqls/*.xml
  type-aliases-package: com.example.demo.domain.model